# Properties necessary for startup
clients:
  lidarr:
    url: "http://lidarr:8686"
    api-key: "api-key-cds"

  soulseek:
    url: "http://slskd:5030"
    api-key: "spi-key-cds"
    download-dir: "/data/media/music-downloads"

  navidrome:
    url: "http://navidrome"
    username: "root"
    password: "password"